apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibm-quantum-credentials
  namespace: jenkins-agents
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ibm-cloud-secret-store
    kind: SecretStore

  target:
    name: ibm-quantum-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        QISKIT_IBM_TOKEN: "{{ .ibm_quantum_token }}"
        ORG_ID: "{{ .ibm_quantum_org_id }}"

  data:
    - secretKey: ibm_quantum_token
      remoteRef:
        key: ibm-quantum/token       # path in IBM Cloud Secrets Manager
    - secretKey: ibm_quantum_org_id
      remoteRef:
        key: ibm-quantum/org-id
